name: Build and Deploy

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install
      run: |
        npm install elm uglify-js

    - name: Verify uglify-js installation
      run: |
        echo "UglifyJS location:"
        find ./node_modules -name uglify-js -type d
        ls -l ./node_modules/.bin
      
    - name: Build
      run: |
        chmod +x ./optimize.sh
        ./optimize.sh

    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
