name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and build
      run: npm install -g elm

    - name: Run Build
      run: elm make src/Main.elm
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install and build
      run: |
        npm install -g elm
        npm install -g elm-test-rs

    - name: Run Tests 
      run: elm-test-rs
